### ISSUE TITLE
Red underline with h1 elements

### ISSUE THREAD

**Issue by Nathanoid** [cdig/cd-module#16] opened 2015-02-26 17:06 UTC
When testing in IE 11 on a Windows 7 laptop the underline generated by using an h1 element is consistently red instead of gold.

![red-line](https://cloud.githubusercontent.com/assets/8481272/6396900/8d07c824-bd9e-11e4-8436-49c88cb7e23e.jpg)

**Comment by theseanzo** [comment] 2015-02-26 21:49
This is a duplicate of #11

**Closed as completed by theseanzo** 2015-02-26 21:49 UTC
